/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aaudio_MainActivity */

#ifndef _Included_com_example_aaudio_MainActivity
#define _Included_com_example_aaudio_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aaudio_MainActivity
 * Method:    record
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_aaudio_MainActivity_MyRecord
  (JNIEnv *, jobject, jint device_ID);

JNIEXPORT jint JNICALL Java_com_example_aaudio_MainActivity_MyStopRecord
        (JNIEnv *, jobject);

/*
 * Class:     com_example_aaudio_MainActivity
 * Method:    play
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_aaudio_MainActivity_MyPlay
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_example_aaudio_MainActivity_MyStopPlay
        (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
